name: Node.js App Deploy to AKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set image tag based on commit
      id: vars
      run: |
        COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        IMAGE_TAG=nodeapp-${COMMIT_SHA}
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: CKA
        resource-group: Avadhhoot2025

    - name: Log in to Quay.io
      run: echo ""a89XKV/w16tf/AQ/Em8gusoxr181Fz2yFpR6/LQGBbdW9ycKOuoFayXQCU9c4RcM"" | docker login quay.io -u avadhut22 --password-stdin

    - name: Build and Push Docker image to Quay.io
      env:
        QUAY_REPO: quay.io/avadhut22/node-app
      run: |
        docker build -t $QUAY_REPO:$IMAGE_TAG .
        docker push $QUAY_REPO:$IMAGE_TAG

    - name: Update Helm values.yaml with new tag
      run: |
        sed -i "s|repository:.*|repository: quay.io/${{ secrets.QUAY_USERNAME }}/node-app|" ./node-app/values.yaml
        sed -i "s|tag:.*|tag: '$IMAGE_TAG'|" ./node-app/values.yaml

    - name: Commit updated values.yaml
      run: |
        git config --global user.name "avadhutpatil22"
        git config --global user.email "patilavadhut907@gmail.com"
        git add ./node-app/values.yaml
        git commit -m "Update image tag to $IMAGE_TAG"
        git push
