name: Node.js App Deploy to AKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set image tag based on commit
      id: vars
      run: |
        COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        IMAGE_TAG=nodeapp-${COMMIT_SHA}
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Log in to Quay.io
      run: echo "a89XKV/w16tf/AQ/Em8gusoxr181Fz2yFpR6/LQGBbdW9ycKOuoFayXQCU9c4RcM" | docker login quay.io -u avadhut22 --password-stdin

    - name: Build and Push Docker image to Quay.io
      env:
        QUAY_REPO: quay.io/avadhut22/node-app
      run: |
        docker build -t $QUAY_REPO:$IMAGE_TAG .
        docker push $QUAY_REPO:$IMAGE_TAG

    - name: Update Helm values.yaml with new tag
      run: |
        sed -i "s|repository:.*|repository: quay.io/avadhut22/node-app|" ./node-app/values.yaml
        sed -i "s|tag:.*|tag: '$IMAGE_TAG'|" ./node-app/values.yaml

    - name: Configure Git identity
      run: |
        git config --global user.name "avadhutpatil22"
        git config --global user.email "patilavadhut907@gmail.com"

    - name: Create and push branch with updated values.yaml
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        BRANCH_NAME="update-image-tag-${IMAGE_TAG}"
        git checkout -b $BRANCH_NAME
        git add ./node-app/values.yaml
        if ! git diff --quiet; then
          git commit -m "Update image tag to $IMAGE_TAG"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/avadhutpatil22/redhatquay-helm-argocd-demo-2025.git
          git push origin $BRANCH_NAME
        else
          echo "No changes to commit."
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_PAT }}
        commit-message: "Update image tag to ${{ env.IMAGE_TAG }}"
        branch: update-image-tag-${{ env.IMAGE_TAG }}
        base: main
        title: "Update image tag to ${{ env.IMAGE_TAG }}"
        body: |
          This PR updates the Helm chart values.yaml with the new image tag `${{ env.IMAGE_TAG }}`.
        labels: automated-pr
        draft: false
